### ISSUE TITLE
System.TypeLoadException: Method 'IsBucketHistogramMatch' in type 'App.Metrics.Internal.NoOp.NullMetricsFilter' does not have an implementation.

### ISSUE THREAD

**Issue by syamalaids** [wavefrontHQ/wavefront-opentracing-sdk-csharp#70]
I am getting the following exception:

Failed to initialize application.  Exception: System.TypeLoadException: Method 'IsBucketHistogramMatch' in type 'App.Metrics.Internal.NoOp.NullMetricsFilter' from assembly 'App.Metrics.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0d5193a913d1b812' does not have an implementation.
   at App.Metrics.MetricsBuilder..ctor()
   at Wavefront.OpenTracing.SDK.CSharp.WavefrontTracer.InitMetricsHistogramsReporting(WavefrontSpanReporter wfSpanReporter, ApplicationTags applicationTags, TimeSpan reportFrequency, ILoggerFactory loggerFactory, IMetricsRoot& metricsRoot, AppMetricsTaskScheduler& metricsScheduler, HeartbeaterService& heartbeaterService, WavefrontSdkMetricsRegistry& sdkMetricsRegistry)
   at Wavefront.OpenTracing.SDK.CSharp.WavefrontTracer..ctor(IReporter reporter, IList`1 tags, IList`1 samplers, ApplicationTags applicationTags, ISet`1 redMetricsCustomTagKeys, TimeSpan reportFrequency, PropagatorRegistry registry, ILoggerFactory loggerFactory)
   at Wavefront.OpenTracing.SDK.CSharp.WavefrontTracer.Builder.Build()
   at CyraCom_CCSCallFlowEngine.CfeService.CreateWavefrontTracer(String application, String service, Settings settings) in C:\Source\cfe\3x\CyraCom_CCSCallFlowEngine\CfeService.cs:line 150
   at CyraCom_CCSCallFlowEngine.CfeService.InitializeOT(Settings settings) in C:\Source\cfe\3x\CyraCom_CCSCallFlowEngine\CfeService.cs:line 121
   at CyraCom_CCSCallFlowEngine.CfeService.OnInitializeApplication() in C:\Source\cfe\3x\CyraCom_CCSCallFlowEngine\CfeService.cs:line 108

Here is my packages.config:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="App.Metrics" version="4.0.0" targetFramework="net461" />
  <package id="App.Metrics.Abstractions" version="4.3.0" targetFramework="net461" />
  <package id="App.Metrics.Concurrency" version="2.0.1" targetFramework="net452" />
  <package id="App.Metrics.Core" version="4.0.0" targetFramework="net461" />
  <package id="App.Metrics.Formatters.Ascii" version="4.0.0" targetFramework="net461" />
  <package id="App.Metrics.Formatters.Json" version="4.0.0" targetFramework="net461" />
  <package id="C5" version="2.3.0.1" targetFramework="net452" />
  <package id="CyraCom.CCS.CMI" version="3.4.10.204" targetFramework="net452" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="1.0.0" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.6.0" targetFramework="net461" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.2" targetFramework="net461" />
  <package id="Wavefront.AppMetrics.SDK.CSharp" version="3.1.0" targetFramework="net461" />
  <package id="Wavefront.OpenTracing.SDK.CSharp" version="2.1.0" targetFramework="net461" />
  <package id="Wavefront.SDK.CSharp" version="1.7.0" targetFramework="net461" />
</packages>
```

**Comment by syamalaids** [comment]
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="App.Metrics" version="4.0.0" targetFramework="net461" />
  <package id="App.Metrics.Abstractions" version="4.3.0" targetFramework="net461" />
  <package id="App.Metrics.Concurrency" version="2.0.1" targetFramework="net452" />
  <package id="App.Metrics.Core" version="4.0.0" targetFramework="net461" />
  <package id="App.Metrics.Formatters.Ascii" version="4.0.0" targetFramework="net461" />
  <package id="App.Metrics.Formatters.Json" version="4.0.0" targetFramework="net461" />
  <package id="C5" version="2.3.0.1" targetFramework="net452" />
  <package id="CyraCom.CCS.CMI" version="3.4.10.204" targetFramework="net452" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="1.0.0" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.6.0" targetFramework="net461" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.2" targetFramework="net461" />
  <package id="Wavefront.AppMetrics.SDK.CSharp" version="3.1.0" targetFramework="net461" />
  <package id="Wavefront.OpenTracing.SDK.CSharp" version="2.1.0" targetFramework="net461" />
  <package id="Wavefront.SDK.CSharp" version="1.7.0" targetFramework="net461" />
</packages>

**Comment by syamalaids** [comment]
I update all App.Metrics.* packages to be of same version 4.3.0 and issue gone away.
